### ISSUE TITLE
Demo refers to inexistant service graphql.GeneralServices

### ISSUE THREAD

**Issue by diegonc** [shendepu/moqui-graphql-demo#1]
Service `graphql.GeneralServices.get#ListPaginationInterface` no longer exists. It was removed in the commit linked below.

https://github.com/shendepu/moqui-graphql/commit/9c05d2a62da911b451e9693007cc71e98cbcd339
```
ERROR         main .moqui.i.c.ExecutionContextFactoryImpl Error initializing ToolFactory GraphQL
org.moqui.service.ServiceException: Service graphql.GeneralServices.get#ListPaginationInterface not found, specified in service.implements in service graphqldemo.moqui.BasicServices.get#Enums
```

Same issue with `graphql.GeneralServices.mutate#OperationInterface`.
```
ERROR         main .moqui.i.c.ExecutionContextFactoryImpl Error initializing ToolFactory GraphQL
org.moqui.service.ServiceException: Service graphql.GeneralServices.mutate#OperationInterface not found, specified in service.implements in service graphqldemo.mantle.party.PartyServices.create#Person
```

**Comment by shendepu** [comment]
There were significant change on moqui-graphql and helper services in past a year along with I were learning more patterns to use graphql. 

I made commit 9321cf17d74c6b076486d909c8b265452d8d68d1 to run with latest moqui-graphql. 

One of important example in this demo is `partyInterfaceFetcher`. There are several entities in `mantle` can be defined as GraphQL Interface, one is `Party` to be interface of `Organization`, `Person`.
