### ISSUE TITLE
A problem occurred evaluating project ':runtime:component:moqui-graphql'.

### ISSUE THREAD

**Issue by SahooSumitKumar** [shendepu/moqui-graphql-demo#2]
Project with path ':runtime/component/moqui-elasticsearch' could not be found in project ':runtime:component:moqui-graphql'.

**Comment by shendepu** [comment]
`moqui-graphql` add-on depends on `moqui-elasticsearch` add-on, so you need to install `moqui-elasticsearch` as well.

**Comment by SahooSumitKumar** [comment]
after install 'moqui-elasticsearch' add-on with path 'runtime/component/moqui-elasticsearch'. still i am getting the same issue .can you help me on that .
